export const ADD_BOOK = 'ADD_BOOK';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const REMOVE_BOOK = 'REMOVE_BOOK';
export const FETCH_BOOKS = 'FETCH_BOOKS';
export const BOOKS_HAS_ERRORED = 'BOOKS_HAS_ERRORED';
export const BOOKS_IS_LOADING = 'BOOKS_IS_LOADING';
